### ISSUE TITLE
Unable to register user user after Drift.logout(); call. 

### ISSUE THREAD

**Issue by alejandromaju** [Driftt/drift-sdk-android#21]
I need to stop receiving messages for the user that logged out so I call Drift logout method. After I login with a new user and registered for drift, I get the No auth error "We're sorry, an unknown error occurred" when I try to show the drift conversations. I fix it by hard closing the app and opened it again. Drift.logout method disconnects the service instead of just logging out the user.

**Comment by eoinoconnell** [comment]
Hi, thanks for that, that is now fixed in release 1.1.2
