### ISSUE TITLE
Hi we are having a problem with your library,  while calculating isOrgCurrentlyOpen()

### ISSUE THREAD

**Issue by shastrikikitchen** [Driftt/drift-sdk-android#26]
Hi , we are getting  a class cast exception when the widget mode is AUTO , due to which we are getting the awayMessage displayed always. 
This is the exception we are getting
Didn't find class "org.joda.time.DateTimeZone" on path: DexPathList[[zip file "/data/app/com.goalwise.debug-1/base.apk"],nativeLibraryDirectories=[/data/app/com.goalwise.debug-1/lib/arm64, /data/app/com.goalwise.debug-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]].
We have enabled proguard and as suggested, we are keeping  the joda files  and this is the proguard statement for our app.
-keep class drift.com.drift.** {*;}
    -keep class org.joda.** {*;}.
Can you please have a look at what is the issue.

Thank you.

**Comment by eoinoconnell** [comment]
Hi, sorry about the delay, we just released v1.1.5 that should resolve this issue for you, feel free to re-open if you have any other questions

**Comment by shastrikikitchen** [comment]
Thanks, It works fine now.
