### ISSUE TITLE
Badge count not updating in list of conversations

### ISSUE THREAD

**Issue by faizfolio** [Driftt/drift-sdk-android#32]
I am using Drift Android SDK version 1.1.5

If user has any unread messages from agent then its count is shown in the item of that conversation on list of conversation screen.

If user is on the list of conversation screen and he receives a reply for his conversation then the number of unread messages are not updated.

If we come back to this screen from any previous screen the we can see the count updated.

**Comment by eoinoconnell** [comment]
This should now be resolved in v1.2.0
