### ISSUE TITLE
ConversationListWrapper: java.lang.NumberFormatException:

### ISSUE THREAD

**Issue by ashishverma93** [Driftt/drift-sdk-android#38]
I am getting the below error for some users when i open the showConversationActivity :
D/DRIFT_SDK: ConversationListWrapper: java.lang.NumberFormatException: Expected an int but was 2282719965 at line 1 column 994 path $[0].conversation.user.id

**Comment by eoinoconnell** [comment]
Hi, what version of the sdk are you using?

**Comment by ashishverma93** [comment]
'com.github.driftt:drift-sdk-android:v1.2.3' - this one i am using.

**Comment by eoinoconnell** [comment]
Hi,

I believe we have this solved for you, can you try this release and let me know?

'com.github.Driftt:drift-sdk-android:30c01eb665'

Thanks!

**Comment by ashishverma93** [comment]
Hi,

It's not working. Again, same error is coming.
DRIFT_SDK: ConversationListWrapper: java.lang.NumberFormatException: Expected an int but was 2255755296 at line 1 column 996 path $[0].conversation.user.id

**Comment by eoinoconnell** [comment]
Hi, that's strange. Can you clean your build folder and try again?

**Comment by ashishverma93** [comment]
I have clean and rebuild the project, also invalidate cache and restart done, still error is coming.
This error is not coming for every user, only for some users. 
It's displaying Dialog message : Title : "Error" Description : "Failed to load conversations"

**Comment by eoinoconnell** [comment]
Hi, I just release v1.2.5 that should resolve this issue for you

**Comment by ashishverma93** [comment]
Hi,
Now it's working. Thanks.
