### ISSUE TITLE
Cannot open Conversation Screen, if user was registered without email id.

### ISSUE THREAD

**Issue by anirudha-banerjee** [Driftt/drift-sdk-android#48]
After registering user using Drift.registerUser("123748", "sample@gmail.com"), Conversation Activity works, but if i register user without a email id, example Drift.registerUser("123748", "Guest") then while opening Conversation Screen, it says "We are sorry. An unknown error has occurred". Please can someone tell me what am i doing wrong. Also tried the same scenario with the sample code provided in this git repo, same result.

**Comment by eoinoconnell** [comment]
Hi,

Sorry for the delay, the users email address is required to use this sdk I'm afraid as it is used to identify the user.

Thanks,

Eoin
