### ISSUE TITLE
error: cannot find symbol method setLoggerListener((message)-[...]sage))

### ISSUE THREAD

**Issue by ashishverma93** [Driftt/drift-sdk-android#49]
Hi Team,

Not able to send a message from Drift Conversation Activity using dependency version **1.2.5**. 
**Getting error message Dialog: Failed to create conversation.**
When I update the dependency version to **1.2.7**, I am not able to **setupdrift** in my project. I am getting this error while Build the project "**error: cannot find symbol method setLoggerListener((message)-[...]sage))**". My app is live in Production.Please help me to solve the issue ASAP.

**Comment by eoinoconnell** [comment]
Hi,

 Sorry for the delay. There was a brief change in the logger listener in 1.2.7. You can now use a lambda to receive the logs.

```
Drift.Companion.setLoggerListener(message -> {

        });
```

This should resolve your issue by moving to 1.2.7. Let me know if you still experience the issue
