### ISSUE TITLE
Java Source Compatibility

### ISSUE THREAD

**Issue by adtyx** [Driftt/drift-sdk-android#52]
Are we looking to provide backwards support to apps with Java as the primary language for the source code, I think this won't be a big change and I can send a PR if you like.

**Comment by eoinoconnell** [comment]
Hi, Kotlin should work with java no problem, are you seeing a particular issue with the SDK?

**Comment by adtyx** [comment]
I'm really sorry I was trying to directly access a Kotlin static method (i.e. without invoking the Companion).
Thank you so much.
