### ISSUE TITLE
Doesn't load, won't start a new conversation

### ISSUE THREAD

**Issue by camhart** [Driftt/drift-sdk-android#53]
Simply doesn't load, and can't start new conversations.  Toast says an unknown error occured.

**Comment by eoinoconnell** [comment]
Hello, have you followed the steps to setup and register a user before starting a new conversation?

**Comment by camhart** [comment]
Do--why is registration required?  The documentation mentions the method
but doesn't state it as a requirement.

**Comment by eoinoconnell** [comment]
Registration is a required feature of the SDK I'm afraid. It does not support unregistered users.

**Comment by camhart** [comment]
Might want to add that to the documentation :).  Thanks for getting back to
me so fast.

**Comment by eoinoconnell** [comment]
No problem, will get the documentation updated.

Thanks
