### ISSUE TITLE
 how can i post more attributes 

### ISSUE THREAD

**Issue by Phu-Hoang** [Driftt/drift-sdk-android#55]
<img width="765" alt="Screen Shot 2020-01-07 at 6 54 22 PM" src="https://user-images.githubusercontent.com/58963202/71893964-91815000-317f-11ea-8316-4a6c44722a0a.png">

**Comment by eoinoconnell** [comment]
Hello, I'm afraid this is not currently supported. I will mark this as a feature request but we currently don't have it on our roadmap
