### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by ArjunKP10p501** [Driftt/drift-sdk-android#9]
https://js.drift.com/embeds/3000/{embedID}.json

What is the empedID?

**Comment by ArjunKP10p501** [comment]
I got the response code 403.

**Comment by brianmcdon** [comment]
Hi, the embedId can be found in the settings of your Drift account on https://app.drift.com/settings/widget 
It will appear under Settings -> Chat Widget -> Install -> Javascript. At the bottom of the code snippet you will see the embedId as shown in the attached 
<img width="1300" alt="embedid_help" src="https://user-images.githubusercontent.com/1974207/31711530-56edfab0-b3f0-11e7-80a8-656384d2d6ae.png">
image.

**Comment by ArjunKP10p501** [comment]
ok, Thank You.
